ChangeLog update APX checking fixed - wrong file in m4 (ax_with_apxs.m4) APACHE 2.0.x version check by presence of ap_release.h
git-svn-id: file:///data/svn/enum/mod_whoisd/trunk@4934 b60c293d-5e0d-0410-87b2-fb9704ccd4b5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -971,7 +971,8 @@ CXXFLAGS
 CCC
 CXXCPP
 F77
-FFLAGS'
+FFLAGS
+APXS'
 
 
 # Initialize some variables set by options.
@@ -1580,7 +1581,7 @@ Optional Packages:
   --with-tags[=TAGS]      include additional configurations [automatic]
   --with-orbit-prefix=PFX   Prefix where ORBIT is installed (optional)
   --with-orbit-exec-prefix=PFX Exec prefix where ORBIT is installed (optional)
-  --with-apxs=PATH        Path to apxs
+  --with-apxs=APXS        absolute path name of apxs executable
   --with-apr-config       location of apr-config executable
   --with-idldir           Directory with idl [/usr/share/idl/fred/]
   --with-idl              location of idl file containing Whois interface
@@ -1602,6 +1603,7 @@ Some influential environment variables:
   CXXCPP      C++ preprocessor
   F77         Fortran 77 compiler command
   FFLAGS      Fortran 77 compiler flags
+  APXS
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6636,7 +6638,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6639 "configure"' > conftest.$ac_ext
+  echo '#line 6641 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9434,11 +9436,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9437: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9439: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9441: \$? = $ac_status" >&5
+   echo "$as_me:9443: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9724,11 +9726,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9727: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9729: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9731: \$? = $ac_status" >&5
+   echo "$as_me:9733: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9828,11 +9830,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9831: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9833: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9835: \$? = $ac_status" >&5
+   echo "$as_me:9837: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12190,7 +12192,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12193 "configure"
+#line 12195 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12290,7 +12292,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12293 "configure"
+#line 12295 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14710,11 +14712,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14713: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14715: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14717: \$? = $ac_status" >&5
+   echo "$as_me:14719: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14814,11 +14816,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14817: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14819: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14821: \$? = $ac_status" >&5
+   echo "$as_me:14823: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16389,11 +16391,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16392: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16394: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16396: \$? = $ac_status" >&5
+   echo "$as_me:16398: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16493,11 +16495,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16496: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16498: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16500: \$? = $ac_status" >&5
+   echo "$as_me:16502: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18693,11 +18695,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18696: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18698: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18700: \$? = $ac_status" >&5
+   echo "$as_me:18702: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18983,11 +18985,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18986: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18988: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18990: \$? = $ac_status" >&5
+   echo "$as_me:18992: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19087,11 +19089,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19090: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19092: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19094: \$? = $ac_status" >&5
+   echo "$as_me:19096: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22424,34 +22426,35 @@ fi
 # check apxs tool
 
 
-# check for --with-apxs
-{ echo "$as_me:$LINENO: checking for --with-apxs" >&5
+
+    if test -z "$APXS"
+  then
+    { echo "$as_me:$LINENO: checking for --with-apxs" >&5
 echo $ECHO_N "checking for --with-apxs... $ECHO_C" >&6; }
 
 # Check whether --with-apxs was given.
 if test "${with_apxs+set}" = set; then
-  withval=$with_apxs;
-  if test -x "$withval"
-  then
-    { echo "$as_me:$LINENO: result: $withval executable, good" >&5
-echo "${ECHO_T}$withval executable, good" >&6; }
-    APXS=$withval
-  else
-    echo
-    { { echo "$as_me:$LINENO: error: $withval not found or not executable" >&5
-echo "$as_me: error: $withval not found or not executable" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
+  withval=$with_apxs;  if test "$withval" != "yes"
+                  then
+                    APXS="$withval"
+                    { echo "$as_me:$LINENO: result: $withval" >&5
+echo "${ECHO_T}$withval" >&6; }
+                  else
+                    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                  fi
 
 else
-  { echo "$as_me:$LINENO: result: no" >&5
+   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
+
 fi
 
+  fi
 
-# find apxs
-if test -z "$APXS"; then
-  for ac_prog in apxs2 apxs
+    if test -z "$APXS"
+  then
+    for ac_prog in apxs2 apxs
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -22496,12 +22499,47 @@ fi
 
   test -n "$APXS" && break
 done
-test -n "$APXS" || APXS="false"
+test -n "$APXS" || APXS="no"
 
-  test "${APXS}" = "false" && { { echo "$as_me:$LINENO: error: failed to find apxs. Try using --with-apxs" >&5
-echo "$as_me: error: failed to find apxs. Try using --with-apxs" >&2;}
+  fi
+
+if test "$APXS" = "no"; then
+    { { echo "$as_me:$LINENO: error: apxs executable does not exist (use --with-apxs)" >&5
+echo "$as_me: error: apxs executable does not exist (use --with-apxs)" >&2;}
    { (exit 1); exit 1; }; }
 fi
+# check for ap_release.h
+# if present we have a apache 2.0.x and greater (in lower it's not included)
+# syntax of \#define AP_SERVER_MAJORVERSION differ in minor versions
+APXS_INCDIR="`${APXS} -q INCLUDEDIR`"
+as_ac_File=`echo "ac_cv_file_$APXS_INCDIR/ap_release.h" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $APXS_INCDIR/ap_release.h" >&5
+echo $ECHO_N "checking for $APXS_INCDIR/ap_release.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$APXS_INCDIR/ap_release.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  { echo "$as_me:$LINENO: apache version >=2.0.x found" >&5
+echo "$as_me: apache version >=2.0.x found" >&6;}
+else
+  { { echo "$as_me:$LINENO: error: apache version >=2.0.x not found." >&5
+echo "$as_me: error: apache version >=2.0.x not found." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 # check apr-config
 
@@ -22577,8 +22615,9 @@ APACHE_CPPFLAGS="`${apr_config} --cppflags`"
 
 
 #set apache module path
-APACHE_LIBEXECDIR=`${APXS} -q LIBEXECDIR`
-APACHE_LIBEXECDIR=${libdir}${APACHE_LIBEXECDIR#/usr/lib};
+#hack: replacing lib-part of dir with ${libdir} to support prefix install
+APACHE_LEDIR=`${APXS} -q LIBEXECDIR`
+APACHE_LIBEXECDIR=${libdir}${APACHE_LEDIR##${APACHE_LEDIR%/*/*}};
 
 
 # check IDL dir
