Added option --with-unittests to configure, which installs tests into a directory unittests in the destination directory
git-svn-id: file:///data/svn/enum/mod-whoisd/trunk@8582 b60c293d-5e0d-0410-87b2-fb9704ccd4b5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -934,6 +934,8 @@ MODULE_INSTALLDIR
 DATAROOTDIR
 IDLDIR
 IDL
+WITH_UNITTESTS_TRUE
+WITH_UNITTESTS_FALSE
 PORT
 NSHOST
 OBJECTNAME
@@ -1574,6 +1576,7 @@ Optional Packages:
   --with-idldir           Directory with idl [DATAROOTDIR/idl/fred/]
   --with-idl              location of idl file containing Whois interface
                           [IDLDIR/Whois.idl]
+  --with-unittests        Whether to include unittests [default=no]
   --with-port             Port where mod_whoisd listen [43]
   --with-nshost           Location of CORBA nameservice host (host[:port])
                           [localhost]
@@ -6647,7 +6650,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6650 "configure"' > conftest.$ac_ext
+  echo '#line 6653 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9699,11 +9702,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9702: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9705: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9706: \$? = $ac_status" >&5
+   echo "$as_me:9709: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9989,11 +9992,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9992: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9995: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9996: \$? = $ac_status" >&5
+   echo "$as_me:9999: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10093,11 +10096,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10096: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10099: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10100: \$? = $ac_status" >&5
+   echo "$as_me:10103: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12470,7 +12473,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12473 "configure"
+#line 12476 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12570,7 +12573,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12573 "configure"
+#line 12576 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14971,11 +14974,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14974: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14977: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14978: \$? = $ac_status" >&5
+   echo "$as_me:14981: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15075,11 +15078,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15078: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15081: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15082: \$? = $ac_status" >&5
+   echo "$as_me:15085: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16673,11 +16676,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16676: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16679: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16680: \$? = $ac_status" >&5
+   echo "$as_me:16683: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16777,11 +16780,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16780: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16783: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16784: \$? = $ac_status" >&5
+   echo "$as_me:16787: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18997,11 +19000,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19000: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19003: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19004: \$? = $ac_status" >&5
+   echo "$as_me:19007: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19287,11 +19290,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19290: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19293: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19294: \$? = $ac_status" >&5
+   echo "$as_me:19297: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19391,11 +19394,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19394: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19397: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19398: \$? = $ac_status" >&5
+   echo "$as_me:19401: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23053,6 +23056,35 @@ else
 
 fi
 
+
+# unittests
+
+# Check whether --with-unittests was given.
+if test "${with_unittests+set}" = set; then
+  withval=$with_unittests; case "${withval}" in
+				yes) UNITTESTS=true;;
+				no) UNITTESTS=false;;
+				*)  { { echo "$as_me:$LINENO: error: bad value ${withval} for --with-unittests" >&5
+echo "$as_me: error: bad value ${withval} for --with-unittests" >&2;}
+   { (exit 1); exit 1; }; };;
+			esac
+else
+  with_unittests=false
+fi
+
+
+{ echo "$as_me:$LINENO:  -------variable UNITTESTS value : $UNITTESTS " >&5
+echo "$as_me:  -------variable UNITTESTS value : $UNITTESTS " >&6;}
+
+ if test x$UNITTESTS = xtrue; then
+  WITH_UNITTESTS_TRUE=
+  WITH_UNITTESTS_FALSE='#'
+else
+  WITH_UNITTESTS_TRUE='#'
+  WITH_UNITTESTS_FALSE=
+fi
+
+
 as_ac_File=`echo "ac_cv_file_$IDL" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $IDL" >&5
 echo $ECHO_N "checking for $IDL... $ECHO_C" >&6; }
@@ -23492,6 +23524,13 @@ if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_UNITTESTS_TRUE}" && test -z "${WITH_UNITTESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_UNITTESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_UNITTESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24237,6 +24276,8 @@ MODULE_INSTALLDIR!$MODULE_INSTALLDIR$ac_delim
 DATAROOTDIR!$DATAROOTDIR$ac_delim
 IDLDIR!$IDLDIR$ac_delim
 IDL!$IDL$ac_delim
+WITH_UNITTESTS_TRUE!$WITH_UNITTESTS_TRUE$ac_delim
+WITH_UNITTESTS_FALSE!$WITH_UNITTESTS_FALSE$ac_delim
 PORT!$PORT$ac_delim
 NSHOST!$NSHOST$ac_delim
 OBJECTNAME!$OBJECTNAME$ac_delim
@@ -24248,7 +24289,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 79; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 81; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
